#![allow(missing_docs)]
use clap::{App, Arg};

#[macro_use]
extern crate diesel;

mod api;
mod db;
mod usecase;

/// Create custom server, wire it to the autogenerated router,
/// and pass it to the web server.
#[tokio::main]
async fn main() {
  env_logger::init();

  let matches = App::new("server")
    .arg(
      Arg::with_name("https")
        .long("https")
        .help("Whether to use HTTPS or not"),
    )
    .get_matches();

  let addr = "127.0.0.1:50001";

  api::create(addr, matches.is_present("https")).await;
}
